import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useInitializeOnboard, useOnboard } from "@pooltogether/hooks";
import { useEffect } from "react";

const INFURA_ID = process.env.NEXT_PUBLIC_JS_INFURA_ID;

console.log(INFURA_ID);

const Home: NextPage = () => {
  useInitializeOnboard({
    infuraId: INFURA_ID,
    defaultNetworkName: "mainnet",
  });

  const {
    connectWallet,
    disconnectWallet,
    isOnboardReady,
    isWalletConnected,
    address,
    network,
  } = useOnboard();

  useEffect(() => {
    console.log("isOnboardReady", isOnboardReady);
  }, [isOnboardReady]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Sample PoolTogether App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button disabled={!isOnboardReady} onClick={() => connectWallet(null)}>
          Connect Wallet
        </button>
        {isWalletConnected && (
          <>
            <div>Address: {address}</div>
            <div>Network: {network}</div>

            <button onClick={() => disconnectWallet()}>
              Disconnect wallet
            </button>
          </>
        )}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
